Fixed bug on description field
firefly-iii/firefly-iii pull request #8070
Opened 2023-10-17 20:01 UTC by Maxco10

Fixes issue https://github.com/firefly-iii/firefly-iii/issues/8069

Changes in this pull request:
- During the refactoring the description field was lost. Now, I update the RuleRepositories->store function with right code for description field.

@JC5

2023-10-20 08:03 UTC, JC5 commented
A rule does not need to have a description, could you make sure a similar check to the title is added?

2023-10-20 13:23 UTC, Maxco10 commented
@JC5 sorry, but i did not get your comment. Please read the issue.

2023-10-20 13:44 UTC, JC5 requested changes

2023-10-20 13:44 UTC, JC5 commented on app/Repositories/Rule/RuleRepository.php
> +        $rule->description     = $data['description'];
This field can be empty or non-existent. So I would expect this instead:

```
 array_key_exists('description', $data) ? $data['description'] : ''';
```

2023-10-25 09:18 UTC, Maxco10 commented
@JC5 PR Updated. I added check on title field, if the title does not exists, we set a default value "untitle", similar case for description field but the default value for this case is "" an empty string.

2023-10-25 09:52 UTC, JC5 commented
Could you fix the spelling of "Untitled" and use single quotes instead of double?

2023-10-25 09:58 UTC, Maxco10 commented
@JC5 Done!

2023-10-26 06:06 UTC, merged